
stimlist1 = 'C:\Users\Ping\Documents\MATLAB\Xblaster3_Chamber3_GIT\Stimulus_Files\Call_Types\Call_Types_list.txt';
stimlist2 = 'C:\Users\Ping\Documents\MATLAB\Xblaster3_Chamber3_GIT\Stimulus_Files\Phee\phee_list.txt';
stimlist3 = 'C:\Users\Ping\Documents\MATLAB\Xblaster3_Chamber3_GIT\Stimulus_Files\Trill\trill_list.txt';

figspec = figure;
set(gcf, 'PaperUnits', 'inches');
set(gcf, 'PaperSize', [17.2*0.3937, 21.5*0.3937]);
set(gcf,'PaperPositionMode','manual')
set(gcf,'PaperPosition', [0 0 17.2*0.3937, 21.5*0.3937]);
set(gcf,'Units','inches');
set(gcf,'Position',[0 0 17.2*0.3937, 21.5*0.3937]);
figparams.fsize = 7;
figparams.fsize_big = figparams.fsize+2;
figparams.msize = 7;
figparams.res = 300;   % DPI
figparams.fontchoice = 'Arial';
lmargin = 0.1;
bmargin =0.08;
intercol = 0.07;
width = 0.4;

fontstr_l = {'FontSize',figparams.fsize+2,'FontWeight','bold','FontName',figparams.fontchoice};

callnames = {'phee',...
             'phee rev',...
             'trill',...
             'trill rev',...
             'trillphee',...
             'trillphee rev',...
             'twitter',...
             'twitter rev',...
             'phee-dtwitter',...
             'phee-dtwitter rev',...
             '?',...
             '?',...
             'tsik-ek',...
             'tsik-ek rev',...
             'tsik-ek',...
             'tsik-ek rev',...
             'trill-twitter-peep',...
             'trill-twitter-peep rev',...
             'dpeep string',...
             'dpeep string rev'};

pos1 = [lmargin, bmargin, width, 0.86];
[xl1,tih(1)] = plot_stimspecs(stimlist1, '1:20',figspec, pos1, figparams, callnames,...
    'Mixed Vocalizations List', 1, 1);
xshift = 0.08;
annotation('textbox',[pos1(1)-xshift, pos1(2)+pos1(4), .05, .05],...
    'String','A','EdgeColor','none',fontstr_l{:});

pos2 = [lmargin+0.4+intercol, bmargin+0.48, width, 0.38];
[xl2,tih(2)] = plot_stimspecs(stimlist2, '1:10',figspec, pos2, figparams, {},...
    'Phee Call Type List', 1, 0);
xlmax = max(xl1,xl2);
xshift = 0.02;
annotation('textbox',[pos2(1)-xshift, pos1(2)+pos1(4), .05, .05],...
    'String','B','EdgeColor','none',fontstr_l{:});

pos3 = [lmargin+0.4+intercol, bmargin, width, 0.38];
[xl3,tih(3)] = plot_stimspecs(stimlist3, '1:10',figspec, pos3, figparams, {},...
    'Trill Call Type List', 1, 0);
annotation('textbox',[pos3(1)-xshift, pos3(2)+pos3(4), .05, .05],...
    'String','C','EdgeColor','none',fontstr_l{:});

axs = findobj(gcf, 'Type','axes');
set(axs,'Xlim',[0 xlmax]); 

for i = 1:length(tih)
    postemp = get(tih(i),'Position');
    postemp(1) = 1/2*xlmax;
    postemp(2) = 28;
    set(tih(i), 'Position', postemp);
end

%print('C:\Users\Ping\Desktop\Wang_lab\Paper_writing\Figures\Supp\Spectall.tif','-dpng','-painters');
